server:
  port: 8082

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/hackathon
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

txn:
  enricher:
    kafkaClusterURL: localhost:9092
    kafkaEnrichTxnInputTopic: enrich-txn-input
    kafkaEnrichTxnOutputTopic: enrich-txn-output
    kafkaConsumerGroupName: txn-enricher
    restRetryCount: 5
    restBackoffTime: 100
    maxPollSize: 3

