server:
  port: 8083

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hackathon
    password: admin
    hikari:
      schema: cloudtechies
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

txn:
  enricher:
    kafkaClusterURL: localhost:9092
    kafkaEnrichTxnInputTopic: prenrvalid-txn-data-output
    kafkaEnrichTxnOutputTopic: downstream-topic
    kafkaConsumerGroupName: txn-enricher
    restRetryCount: 5
    restBackoffTime: 100
    maxPollSize: 3

